In [6]:
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

# Initialize a 24x24 matrix with zeros
conflict_matrix = np.zeros((24, 24), dtype=int)

# Fill the upper triangle of the matrix with random 0s and 1s
for i in range(24):
    for j in range(i + 1, 24):
        conflict_matrix[i, j] = np.random.choice([0, 1])

# Make the matrix symmetric
conflict_matrix = conflict_matrix + conflict_matrix.T

print(conflict_matrix)


[[0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1]
 [0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1]
 [1 1 0 1 1 0 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1]
 [0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 0]
 [0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
 [0 1 0 0 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 0 1 0 1]
 [1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1]
 [0 1 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1]
 [0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1]
 [0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0]
 [0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 1]
 [0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 1]
 [1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0]
 [1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 1]
 [1 0 0 1 0 1 0 0 1 0 0 0 1 0 1

In [2]:
import pandas as pd

# Create a DataFrame for better visualization
conflict_df = pd.DataFrame(conflict_matrix)
print(conflict_df)

    0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0    0   0   1   0   0   0   1   0   0   0  ...   0   1   0   1   1   1   0   
1    0   0   1   1   1   1   1   1   1   0  ...   0   1   0   0   0   0   0   
2    1   1   0   1   1   0   1   1   0   1  ...   1   0   0   0   0   0   0   
3    0   1   1   0   1   0   1   1   1   1  ...   1   1   0   1   0   1   0   
4    0   1   1   1   0   1   0   1   1   1  ...   1   1   1   1   0   0   1   
5    0   1   0   0   1   0   1   1   1   1  ...   1   0   1   0   1   1   0   
6    1   1   1   1   0   1   0   0   0   1  ...   1   0   0   0   0   0   0   
7    0   1   1   1   1   1   0   0   1   0  ...   0   0   0   1   0   0   0   
8    0   1   0   1   1   1   0   1   0   0  ...   0   1   1   1   0   1   0   
9    0   0   1   1   1   1   1   0   0   0  ...   1   0   0   0   0   0   0   
10   1   0   0   0   1   0   1   1   1   0  ...   0   1   0   0   0   0   0   
11   0   1   1   1   1   1   0   1   0   0  ...   0 

In [5]:
import random

first_names = ["Ali", "Zahra", "Reza", "Sara", "Mohammad", "Fatemeh", "Hossein", "Maryam", "Mehdi", "Narges", "Hamed", "Roya"]
last_names = ["Ahmadi", "Hosseini", "Karimi", "Rahimi", "Hashemi", "Ebrahimi", "Moradi", "Mohammadi", "Rostami", "Fazeli", "Hosseinzadeh", "Niknam"]

# Set a seed for reproducibility
random.seed(42)

# Generate 24 random names
random_names = []
for _ in range(24):
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    random_names.append(f"{first_name} {last_name}")

# Print the random names
for name in random_names:
    print(name)


Hamed Hosseini
Ali Niknam
Mohammad Rahimi
Sara Karimi
Roya Hosseini
Hamed Niknam
Mehdi Hosseini
Narges Moradi
Ali Ahmadi
Zahra Rahimi
Sara Rostami
Narges Ahmadi
Mehdi Rahimi
Roya Hosseinzadeh
Roya Rostami
Hossein Rahimi
Maryam Fazeli
Mohammad Ahmadi
Reza Niknam
Hossein Ebrahimi
Mohammad Karimi
Sara Ebrahimi
Zahra Hosseini
Hossein Hosseini


In [22]:
import numpy as np
import pandas as pd
import random

# List of first names and last names
first_names = ["Ali", "Zahra", "Reza", "Sara", "Mohammad", "Fatemeh", "Hossein", "Maryam", "Mehdi", "Narges", "Hamed", "Roya"]
last_names = ["Ahmadi", "Hosseini", "Karimi", "Rahimi", "Hashemi", "Ebrahimi", "Moradi", "Mohammadi", "Rostami", "Fazeli", "Hosseinzadeh", "Niknam"]

# Set a seed for reproducibility
random.seed(42)

# Generate 24 unique random names
random_names = set()
while len(random_names) < 24:
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    random_names.add(f"{first_name} {last_name}")

random_names = list(random_names)  # Convert set to list

# Initialize a 24x24 matrix with zeros
conflict_matrix = np.zeros((24, 24), dtype=int)

# Randomly select 40 unique pairs for conflicts
conflict_pairs = set()
while len(conflict_pairs) < 40:
    i = random.randint(0, 23)
    j = random.randint(0, 23)
    if i != j and (i, j) not in conflict_pairs and (j, i) not in conflict_pairs:
        conflict_pairs.add((i, j))

# Assign conflicts to the matrix
for i, j in conflict_pairs:
    conflict_matrix[i, j] = 1

# Make the matrix symmetric
conflict_matrix = conflict_matrix + conflict_matrix.T
print(conflict_matrix)
# Create a DataFrame with the conflict matrix
conflict_df = pd.DataFrame(conflict_matrix, index=random_names, columns=random_names)

# Display the DataFrame
# print(conflict_df)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 0 0

In [23]:
import numpy as np
import pandas as pd
import random

# List of first names and last names
first_names = ["Ali", "Zahra", "Reza", "Sara", "Mohammad", "Fatemeh", "Hossein", "Maryam", "Mehdi", "Narges", "Hamed", "Roya"]
last_names = ["Ahmadi", "Hosseini", "Karimi", "Rahimi", "Hashemi", "Ebrahimi", "Moradi", "Mohammadi", "Rostami", "Fazeli", "Hosseinzadeh", "Niknam"]

# Set a seed for reproducibility
random.seed(42)

# Generate 24 unique random names
random_names = set()
while len(random_names) < 24:
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    random_names.add(f"{first_name} {last_name}")

random_names = list(random_names)  # Convert set to list

# Initialize a 24x24 matrix with zeros
conflict_matrix = np.zeros((24, 24), dtype=int)

# Randomly select 40 unique pairs for conflicts
conflict_pairs = set()
while len(conflict_pairs) < 40:
    i = random.randint(0, 23)
    j = random.randint(0, 23)
    if i != j and (i, j) not in conflict_pairs:
        conflict_pairs.add((i, j))

# Assign conflicts to the matrix
for i, j in conflict_pairs:
    conflict_matrix[i, j] = 1

# Create a DataFrame with the conflict matrix
conflict_df = pd.DataFrame(conflict_matrix, index=random_names, columns=random_names)

# Display the DataFrame
print(conflict_df)


                   Narges Moradi  Mehdi Hosseini  Roya Hosseini  Reza Niknam  \
Narges Moradi                  0               0              0            0   
Mehdi Hosseini                 0               0              0            0   
Roya Hosseini                  0               0              0            0   
Reza Niknam                    0               0              0            0   
Zahra Hosseini                 0               0              0            0   
Ali Niknam                     0               0              0            0   
Hossein Ebrahimi               0               0              0            0   
Sara Karimi                    0               0              0            0   
Narges Ahmadi                  0               0              0            0   
Hossein Rahimi                 0               0              0            0   
Roya Rostami                   0               0              0            0   
Zahra Rahimi                   0        

In [24]:
import random
import pandas as pd

random_names = list(random_names)  # Convert set to list

# Shuffle the names to ensure randomness
random.shuffle(random_names)

# Create a 6x4 matrix with the shuffled names
seating_matrix = [random_names[i * 4:(i + 1) * 4] for i in range(6)]

# Convert the seating matrix to a DataFrame for better visualization
seating_df = pd.DataFrame(seating_matrix)

# Display the DataFrame
print(seating_df)


                  0                  1                 2                3
0     Narges Ahmadi      Narges Moradi        Ali Niknam     Hamed Niknam
1        Ali Ahmadi  Roya Hosseinzadeh   Mohammad Karimi     Mehdi Rahimi
2  Hossein Hosseini     Hossein Rahimi  Hossein Ebrahimi  Mohammad Rahimi
3    Hamed Hosseini       Sara Rostami      Roya Rostami    Sara Ebrahimi
4       Reza Niknam     Mehdi Hosseini     Roya Hosseini    Maryam Fazeli
5   Mohammad Ahmadi     Zahra Hosseini       Sara Karimi     Zahra Rahimi


In [25]:
# Function to get "+" pattern pairs
def get_plus_pattern_pairs(matrix, center_i, center_j):
    pairs = []
    center = matrix[center_i][center_j]
    # Top
    if center_i > 0:
        top = matrix[center_i - 1][center_j]
        pairs.append((center, top))
    # Bottom
    if center_i < len(matrix) - 1:
        bottom = matrix[center_i + 1][center_j]
        pairs.append((center, bottom))
    # Left
    if center_j > 0:
        left = matrix[center_i][center_j - 1]
        pairs.append((center, left))
    # Right
    if center_j < len(matrix[0]) - 1:
        right = matrix[center_i][center_j + 1]
        pairs.append((center, right))
    return pairs

# Move the "+" kernel from (0,0) to (3,3)
steps = []
for i in range(6):  # From row 0 to row 3
    for j in range(4):  # From column 0 to column 3
        pairs = get_plus_pattern_pairs(seating_matrix, i, j)
        steps.append(((i, j), pairs))

# Display the pairs for each step
for step, pairs in steps:
    print(f"Step at center ({step[0]},{step[1]}):")
    for pair in pairs:
        print(f"  {pair[0]} with {pair[1]}")

Step at center (0,0):
  Narges Ahmadi with Ali Ahmadi
  Narges Ahmadi with Narges Moradi
Step at center (0,1):
  Narges Moradi with Roya Hosseinzadeh
  Narges Moradi with Narges Ahmadi
  Narges Moradi with Ali Niknam
Step at center (0,2):
  Ali Niknam with Mohammad Karimi
  Ali Niknam with Narges Moradi
  Ali Niknam with Hamed Niknam
Step at center (0,3):
  Hamed Niknam with Mehdi Rahimi
  Hamed Niknam with Ali Niknam
Step at center (1,0):
  Ali Ahmadi with Narges Ahmadi
  Ali Ahmadi with Hossein Hosseini
  Ali Ahmadi with Roya Hosseinzadeh
Step at center (1,1):
  Roya Hosseinzadeh with Narges Moradi
  Roya Hosseinzadeh with Hossein Rahimi
  Roya Hosseinzadeh with Ali Ahmadi
  Roya Hosseinzadeh with Mohammad Karimi
Step at center (1,2):
  Mohammad Karimi with Ali Niknam
  Mohammad Karimi with Hossein Ebrahimi
  Mohammad Karimi with Roya Hosseinzadeh
  Mohammad Karimi with Mehdi Rahimi
Step at center (1,3):
  Mehdi Rahimi with Hamed Niknam
  Mehdi Rahimi with Mohammad Rahimi
  Mehdi Rah

In [29]:
# Assuming conflict_matrix is defined and indexed by user names

# Function to get "+" pattern pairs with conflict scores
# Assuming conflict_matrix is defined and indexed by user names
# Assuming seating_matrix is indexed by user names

# Function to get "+" pattern pairs with conflict scores
def get_plus_pattern_pairs_with_conflict(matrix, conflict_matrix, center_i, center_j):
    pairs = []
    center_user = matrix[center_i][center_j]
    # Top
    if center_i > 0:
        top_user = matrix[center_i - 1][center_j]
        conflict_score = conflict_matrix.loc[center_user, top_user]
        pairs.append(((center_user, top_user), conflict_score))
    # Bottom
    if center_i < len(matrix) - 1:
        bottom_user = matrix[center_i + 1][center_j]
        conflict_score = conflict_matrix.loc[center_user, bottom_user]
        pairs.append(((center_user, bottom_user), conflict_score))
    # Left
    if center_j > 0:
        left_user = matrix[center_i][center_j - 1]
        conflict_score = conflict_matrix.loc[center_user, left_user]
        pairs.append(((center_user, left_user), conflict_score))
    # Right
    if center_j < len(matrix[0]) - 1:
        right_user = matrix[center_i][center_j + 1]
        conflict_score = conflict_matrix.loc[center_user, right_user]
        pairs.append(((center_user, right_user), conflict_score))
    return pairs

# Move the "+" kernel from (0,0) to (3,3)
steps = []
for i in range(6):  # From row 0 to row 5
    for j in range(4):  # From column 0 to column 3
        pairs_with_conflict = get_plus_pattern_pairs_with_conflict(seating_matrix, conflict_df, i, j)
        steps.append(((i, j), pairs_with_conflict))

# Display the pairs for each step
for step, pairs_with_conflict in steps:
    print(f"Step at center ({step[0]},{step[1]}):")
    for pair, conflict_score in pairs_with_conflict:
        print(f"  {pair[0]} with {pair[1]} - Conflict Score: {conflict_score}")


# Move the "+" kernel from (0,0) to (3,3)
steps = []
for i in range(6):  # From row 0 to row 5
    for j in range(4):  # From column 0 to column 3
        pairs_with_conflict = get_plus_pattern_pairs_with_conflict(seating_matrix, conflict_df, i, j)
        steps.append(((i, j), pairs_with_conflict))

# Display the pairs for each step
for step, pairs_with_conflict in steps:
    print(f"Step at center ({step[0]},{step[1]}):")
    for pair, conflict_score in pairs_with_conflict:
        print(f"  {pair[0]} with {pair[1]} - Conflict Score: {conflict_score}")

Step at center (0,0):
  Narges Ahmadi with Ali Ahmadi - Conflict Score: 0
  Narges Ahmadi with Narges Moradi - Conflict Score: 0
Step at center (0,1):
  Narges Moradi with Roya Hosseinzadeh - Conflict Score: 0
  Narges Moradi with Narges Ahmadi - Conflict Score: 0
  Narges Moradi with Ali Niknam - Conflict Score: 0
Step at center (0,2):
  Ali Niknam with Mohammad Karimi - Conflict Score: 0
  Ali Niknam with Narges Moradi - Conflict Score: 0
  Ali Niknam with Hamed Niknam - Conflict Score: 0
Step at center (0,3):
  Hamed Niknam with Mehdi Rahimi - Conflict Score: 0
  Hamed Niknam with Ali Niknam - Conflict Score: 0
Step at center (1,0):
  Ali Ahmadi with Narges Ahmadi - Conflict Score: 0
  Ali Ahmadi with Hossein Hosseini - Conflict Score: 0
  Ali Ahmadi with Roya Hosseinzadeh - Conflict Score: 0
Step at center (1,1):
  Roya Hosseinzadeh with Narges Moradi - Conflict Score: 0
  Roya Hosseinzadeh with Hossein Rahimi - Conflict Score: 0
  Roya Hosseinzadeh with Ali Ahmadi - Conflict Score

In [30]:
# Initialize a matrix to store the summed-up conflicts for each step
summed_matrix = [[0] * 4 for _ in range(6)]

# Move the "+" kernel from (0,0) to (3,3) and sum up conflicts for each step
for i in range(6):  # From row 0 to row 5
    for j in range(4):  # From column 0 to column 3
        pairs_with_conflict = get_plus_pattern_pairs_with_conflict(seating_matrix, conflict_df, i, j)
        summed_conflicts = sum(conflict_score for _, conflict_score in pairs_with_conflict)
        summed_matrix[i][j] = summed_conflicts

# Create a DataFrame from the summed-up conflicts matrix
summed_df = pd.DataFrame(summed_matrix)

# Display the summed-up conflicts DataFrame
print("Summed-up Conflicts Matrix:")
print(summed_df)

Summed-up Conflicts Matrix:
   0  1  2  3
0  0  0  0  0
1  0  1  0  0
2  0  0  0  0
3  0  1  1  1
4  1  0  1  0
5  0  0  0  0
